#!/bin/bash

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║   🧪 TEST WHOP BADGE - Step by Step                          ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Follow these steps to see the LIVE badge:"
echo ""
echo "1️⃣  Start the dev server:"
echo "   yarn dev"
echo ""
echo "2️⃣  Open http://localhost:3000/dashboard"
echo "   → You should NOT see badge (no Whop connected yet)"
echo ""
echo "3️⃣  Go to http://localhost:3000/settings"
echo "   → Scroll to 'Whop Connection' section"
echo "   → Enter any test API key (e.g., 'whop_test123')"
echo "   → Click 'Connect Whop'"
echo "   → You should see 'Whop account connected successfully!' toast"
echo ""
echo "4️⃣  Go back to http://localhost:3000/dashboard"
echo "   → You should NOW see: 'Dashboard ● LIVE: Whop data'"
echo "   → The green dot will pulse!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Badge appearance:"
echo "┌─────────────────────────────────────────┐"
echo "│ Dashboard  [● LIVE: Whop data]          │"
echo "│             ↑ green pulsing dot         │"
echo "└─────────────────────────────────────────┘"
echo ""
